name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: lukechilds/dockerpi:latest
    steps:
    - uses: actions/checkout@v3
    - run: ls
